SELECT A.SALES_DATE as SALES_DATE
     , A.PRODUCT_ID as PRODUCT_ID
     , A.USER_ID  as USER_ID
     , A.SALES_AMOUNT as SALES_AMOUNT
  FROM 
  (SELECT TO_CHAR(OFFLINE_SALE.SALES_DATE, 'yyyy-MM-dd') as SALES_DATE
        , OFFLINE_SALE.PRODUCT_ID as PRODUCT_ID
        , NULL as USER_ID
        , OFFLINE_SALE.SALES_AMOUNT as SALES_AMOUNT
        , OFFLINE_SALE.OFFLINE_SALE_ID as SALE_ID
     FROM OFFLINE_SALE OFFLINE_SALE
   UNION ALL 
   SELECT TO_CHAR(ONLINE_SALE.SALES_DATE, 'yyyy-MM-dd') as SALES_DATE
        , ONLINE_SALE.PRODUCT_ID as PRODUCT_ID
        , ONLINE_SALE.USER_ID as USER_ID
        , ONLINE_SALE.SALES_AMOUNT as SALES_AMOUNT
        , ONLINE_SALE.ONLINE_SALE_ID as SALE_ID
     FROM ONLINE_SALE ONLINE_SALE
  ) A
  WHERE A.SALES_DATE LIKE '2022-03%'
  ORDER BY A.SALES_DATE ASC, A.PRODUCT_ID ASC, A.USER_ID ASC;